// Generated by `npm run generate` from src/v1/index.ts.
// Do not edit: change the schema and regenerate.

export type GrowthStage = 'germination' | 'seedling' | 'vegetative' | 'flowering' | 'drying' | 'curing';

export type MemberRole = 'can_log' | 'can_manage';

export type EntryKind =
  'water' | 'feed' | 'photo' | 'note' | 'measurement' | 'training' | 'phase' | 'move' | 'harvest' | 'visit' | 'alarm' | 'plan' | 'system';

export type EntrySource = 'human' | 'device' | 'plan' | 'preset' | 'alarm';

export type Severity = 'critical' | 'warning' | 'info';

export type AlertKind = 'threshold' | 'offline' | 'camera_stale';

export type WebhookMethod = 'GET' | 'POST' | 'PUT';

export type NotificationChannel = 'email' | 'push' | 'telegram' | 'webhook';

export type PlanTransitionKind = 'confirm' | 'skip' | 'extend' | 'pause' | 'resume';

export type SocketRole =
  | ''
  | 'dehumidifier'
  | 'heater'
  | 'light'
  | 'secondary_light'
  | 'co2'
  | 'humidifier'
  | 'exhaust'
  | 'circulation'
  | 'fan'
  | 'pump'
  | 'custom_timer'
  | 'manual';

export type ValueState = 'live' | 'stale' | 'offline';

export type CameraKind = 'terpcam_controller' | 'terpcam_standalone' | 'rtsp';

export type MediaKind = 'still' | 'timelapse' | 'photo' | 'avatar' | 'export';

export type GrantKind = 'included' | 'migration' | 'purchase';

export type PlanStatus = 'running' | 'paused' | 'stopped' | 'completed';

export type SpaceKind = 'tent' | 'fridge' | 'room' | 'balcony' | 'other';

export type GrowType = 'photoperiod' | 'autoflower';

export type ReminderKind = 'water' | 'feed' | 'chore' | 'custom';

export type ShareKind = 'view' | 'public_page';

export type GrowOrSpaceType = 'grow' | 'space';

export type TemperatureUnit = 'celsius' | 'fahrenheit';

export type WeightUnit = 'grams' | 'ounces';

export type VolumeUnit = 'liters' | 'gallons';

export type Metric = 'temperature' | 'humidity' | 'co2' | 'leafTemperature' | 'lux' | 'vpd' | 'ppfd' | 'offline';

export type OutputMetric = 'heater' | 'dehumidifier' | 'co2' | 'light' | 'fan' | 'relais' | 'fanInternal' | 'fanExternal' | 'fanBackwall';

export type NotificationCategory = 'alerts' | 'warnings' | 'tasks' | 'plan' | 'weekly_timelapse';

export type NotificationSubjectType = 'alert' | 'task' | 'plan' | 'media';

export type ExportStatus = 'queued' | 'running' | 'ready' | 'failed';

export type FirmwareChannel = 'stable' | 'beta' | 'alpha' | 'manual';

export type SocketState = 'on' | 'off' | 'unknown';

export type SocketOverrideState = 'on' | 'off' | 'auto';

export type DeviceCommand =
  RebootCommand | MaintenanceCommand | TestCommand | StopTestCommand | CaptureStillCommand | SocketOverrideCommand | SocketSetCommand;

export type DurationUnit = 'minutes' | 'hours' | 'days' | 'weeks';

export type PlanNotifyMode = 'off' | 'on_step' | 'on_confirmation';

export type PlanTransition =
  | {
      kind: 'confirm';
    }
  | {
      kind: 'skip';
    }
  | {
      kind: 'extend';
      by: StepDuration;
    }
  | {
      kind: 'pause';
      reason: string | null;
    }
  | {
      kind: 'resume';
    };

export type AlarmOrigin = 'preset' | 'always' | 'device' | 'human';

export type AlarmDeliveryMode = 'routing' | 'custom';

export type AlarmDeliveryChannel = 'email' | 'webhook';

export type AlarmWatch = ReadingWatch | OutputLevelWatch | OutputRunningWatch;

export type AdminLogLevel = 'error' | 'warn' | 'info';

export type PresetPrompt = 'ask' | 'never';

export type AccessNeed = 'own' | 'manage' | 'log' | 'view';

export type PhaseSource = 'preset' | 'plan' | 'human';

export type GrowSchemeOrigin =
  | {
      type: 'asset';
      assetId: string;
      /**
       * The asset version the grid was taken from, so an edited asset never rewrites a past grow.
       */
      version: string;
    }
  | {
      type: 'own';
      schemeId: string;
    };

export type GrowVisibility = 'private' | 'public';

export type PlantStatus = 'active' | 'harvested' | 'ended';

export type TaskSource = 'reminder' | 'scheme' | 'plan_step' | 'plan_suggestion';

export type GrowDecision = 'start_grow' | 'move_grow' | 'climate_only';

export type PresetPlanEffect = 'none' | 'skipped' | 'paused';

export type EntryValues =
  | WaterEntryValues
  | FeedEntryValues
  | MeasurementEntryValues
  | PhotoEntryValues
  | NoteEntryValues
  | TrainingEntryValues
  | VisitEntryValues
  | SystemEntryValues
  | AlarmEntryValues
  | PhaseEntryValues
  | MoveEntryValues
  | HarvestEntryValues
  | PlanEntryValues;

export type HumanEntryKind = 'water' | 'feed' | 'photo' | 'note' | 'measurement' | 'training' | 'visit';

export type EntryValuesDraft =
  | {
      kind: 'water';
      litres?: number | null;
      readings?: EntryReading[];
    }
  | {
      kind: 'feed';
      litres?: number | null;
      /**
       * The row of the grid the doses were read from; null when the grow feeds without a scheme.
       */
      schemeWeek?: number | null;
      doses?: EntryDose[];
      readings?: EntryReading[];
    }
  | {
      kind: 'measurement';
      readings?: EntryReading[];
    }
  | PhotoEntryValues
  | NoteEntryValues
  | TrainingEntryValues
  | VisitEntryValues;

export type MediaWindow = 'day' | 'week' | 'month' | 'phase' | 'grow' | 'custom';

export type MediaQuality = 'sd' | 'hd';

export type MediaAspect = '16_9' | '9_16' | '1_1';

export type MediaRenderStatus = 'queued' | 'rendering' | 'ready' | 'failed';

export type ExportScope = 'grow' | 'account';

export type UploadMediaKind = 'photo' | 'avatar';

export type CameraTransport = 'tcp' | 'udp';

export type CameraModel = 'terp_cam' | 'tapo_c200' | 'reolink' | 'hikvision' | 'custom';

export type EntitlementTier = 'free' | 'premium';

export type CameraCreate = ControllerCameraCreate | StandaloneCameraCreate | RtspCameraCreate;

export type ChartViewSpan =
  | {
      kind: 'last';
      forSeconds: number;
    }
  | {
      kind: 'fixed';
      range: TimeRange;
    }
  | {
      kind: 'phase';
    }
  | {
      kind: 'grow';
    };

export type ChartViewLayout = 'stacked' | 'overlay' | 'day_of_grow';

export type VerdictRating = 'good' | 'watch' | 'poor';

export type TimelineRange = '24h' | '7d' | 'phase' | 'grow';

export type GrowSeriesRange = '24h' | '7d' | 'phase' | 'grow' | 'custom';

export type SharedSubject = SharedGrow | SharedSpace;


export interface ProblemError {
  /**
   * Dotted path into the request body.
   */
  field: string;
  code: string;
  detail: string;
}

export interface Problem {
  status: number;
  /**
   * Stable, machine-readable; what a client branches on.
   */
  code: string;
  title: string;
  detail: string;
  /**
   * Per-field validation failures; empty for every other error.
   */
  errors: ProblemError[];
}

export interface Person {
  id: string;
  handle: string;
}

export interface MetricValue {
  /**
   * null when the device has never reported this metric.
   */
  value: number | null;
  measuredAt: string | null;
  state: ValueState;
}

export interface SeriesPoint {
  measuredAt: string;
  value: number | null;
}

export interface GrowOrSpaceRef {
  type: GrowOrSpaceType;
  id: string;
}

export interface UnitPreference {
  temperature: TemperatureUnit;
  weight: WeightUnit;
  volume: VolumeUnit;
}

export interface SchemeAmount {
  productKey: string;
  name: string;
  /**
   * Null is "not this week".
   */
  value: number | null;
  /**
   * The scheme's own unit, such as `ml/l`; never converted.
   */
  unit: string;
}

export interface SchemeWeek {
  /**
   * 1-based, counted from the start of the grow.
   */
  week: number;
  stage: GrowthStage | null;
  /**
   * mS/cm on zero-EC water; null where the chart publishes none.
   */
  ecTarget?: number | null;
  amounts: SchemeAmount[];
}

export interface UserPrivacy {
  hideWeights: boolean;
  hideCounts: boolean;
}

export interface UserPreferences {
  units: UnitPreference;
  locale: string;
  timezone: string;
}

export interface UserRetention {
  climateDays: number | null;
}

export interface WebhookChannel {
  url: string;
  method: WebhookMethod;
  headers: {
    [k: string]: string;
  };
}

export interface TelegramChannel {
  chatId: string;
  linkedAt: string;
}

export interface NotificationChannels {
  email: string | null;
  telegram: TelegramChannel | null;
  webhook: WebhookChannel | null;
}

export interface NotificationRouting {
  [k: string]: NotificationChannel[];
}

export interface QuietHours {
  fromMinute: number;
  toMinute: number;
}

export interface NotificationSettings {
  channels: NotificationChannels;
  routing: NotificationRouting;
  quietHours: QuietHours | null;
  /**
   * Mutes every category, critical alarms included, for this person only.
   */
  mutedUntil: string | null;
}

export interface User {
  id: string;
  createdAt: string;
  email: string;
  isAdmin: boolean;
  isActive: boolean;
  activationCode: string | null;
  handle: string;
  bio: string | null;
  avatarMediaId: string | null;
  /**
   * Whether /@handle answers with a page at all.
   */
  publicProfile: boolean;
  privacy: UserPrivacy;
  preferences: UserPreferences;
  retention: UserRetention;
  notifications: NotificationSettings;
  /**
   * Set when deletion begins; it is resumable, so it outlives one request.
   */
  deletionStartedAt: string | null;
}

export interface PremiumFree {
  /**
   * The width a free camera's stills are served at; null is the stored picture whole.
   */
  stillWidth: number | null;
  /**
   * How long a free camera's stills are kept; null is for as long as an entitled one's.
   */
  stillDays: number | null;
  timelapseDays: number | null;
}

export interface Premium {
  enforced: boolean;
  extendUrl: string | null;
  priceLabel: string | null;
  free: PremiumFree;
}

export interface Me {
  id: string;
  createdAt: string;
  email: string;
  isAdmin: boolean;
  isActive: boolean;
  handle: string;
  bio: string | null;
  avatarMediaId: string | null;
  /**
   * Whether /@handle answers with a page at all.
   */
  publicProfile: boolean;
  privacy: UserPrivacy;
  preferences: UserPreferences;
  retention: UserRetention;
  notifications: NotificationSettings;
  /**
   * Set when deletion begins; it is resumable, so it outlives one request.
   */
  deletionStartedAt: string | null;
  premium: Premium;
  /**
   * VAPID public key; null until the install configures a key pair.
   */
  pushPublicKey: string | null;
  telegramAvailable: boolean;
  /**
   * Whether any browser of this account is subscribed to push, so a screen can say whether the push row of the grid goes anywhere.
   */
  pushSubscribed: boolean;
}

export interface MeUpdate {
  handle?: string;
  bio?: string | null;
  avatarMediaId?: string | null;
  /**
   * Whether /@handle answers with a page at all.
   */
  publicProfile?: boolean;
  privacy?: UserPrivacy;
  preferences?: UserPreferences;
  retention?: UserRetention;
  notifications?: NotificationSettings;
}

export interface PasswordChange {
  currentPassword: string;
  newPassword: string;
}

export interface UserCreate {
  email: string;
  handle: string;
  password: string;
}

export interface SignupUser {
  id: string;
  createdAt: string;
  email: string;
  handle: string;
  isActive: boolean;
}

export interface UserActivation {
  activationCode: string;
}

export interface AuthToken {
  token: string;
  validUntil: string;
}

export interface SessionTokens {
  userToken: AuthToken;
  refreshToken: AuthToken;
  mediaToken: AuthToken;
}

export interface Session {
  id: string;
  createdAt: string;
  userId: string;
  userAgent: string | null;
  lastSeenAt: string;
  expiresAt: string;
}

export interface SessionPage {
  items: Session[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface SessionCreate {
  email: string;
  password: string;
  /**
   * Absent means a session that ends with the browser.
   */
  stayLoggedIn?: boolean;
}

export interface SessionUser {
  id: string;
  handle: string;
  isAdmin: boolean;
  isDemo: boolean;
}

export interface SessionResult {
  userToken: AuthToken;
  refreshToken: AuthToken;
  mediaToken: AuthToken;
  sessionId: string;
  user: SessionUser;
}

export interface DemoSessionCreate {}

export interface SessionRefresh {
  refreshToken: string;
}

export interface AutomationSessionCreate {
  token: string;
}

export interface AutomationSession {
  userToken: AuthToken;
}

export interface PasswordResetCreate {
  email: string;
}

export interface PasswordResetRedemption {
  password: string;
}

export interface PushSubscriptionKeys {
  p256dh: string;
  auth: string;
}

export interface PushSubscription {
  id: string;
  createdAt: string;
  userId: string;
  endpoint: string;
  keys: PushSubscriptionKeys;
  /**
   * Which browser this subscription is, so that a person can tell two apart.
   */
  userAgent: string | null;
}

export interface PushSubscriptionCreate {
  endpoint: string;
  keys: PushSubscriptionKeys;
}

export interface TelegramLink {
  url: string;
  validUntil: string;
}

export interface NotificationLogEntry {
  id: string;
  createdAt: string;
  userId: string;
  channel: NotificationChannel;
  category: NotificationCategory;
  subject: {
    type: NotificationSubjectType;
    id: string;
  };
  externalMessageId: string | null;
  sentAt: string;
  expiresAt: string;
}

export interface UserExport {
  id: string;
  createdAt: string;
  status: ExportStatus;
  startedAt: string | null;
  endedAt: string | null;
  downloadUrl: string | null;
  /**
   * When the finished file is swept; null while it is still being made.
   */
  validUntil: string | null;
  /**
   * Why it failed; null otherwise.
   */
  detail: string | null;
}

export interface AdminUserPage {
  items: User[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface AdminUserCreate {
  email: string;
  handle: string;
  password: string;
  isAdmin?: boolean;
  isActive?: boolean;
}

export interface AdminUserUpdate {
  email?: string;
  handle?: string;
  password?: string;
  isAdmin?: boolean;
  isActive?: boolean;
}

export interface PushPayload {
  title: string;
  body: string;
  category: NotificationCategory;
  subject: {
    type: NotificationSubjectType;
    id: string;
  };
  severity: Severity;
  /**
   * Where the subject is looked at, for a subject its own id cannot address.
   */
  cameraId: string | null;
}

export interface DeviceConfiguration {
  [k: string]: any;
}

export interface DeviceFirmwareTarget {
  channel: FirmwareChannel;
  /**
   * The build this device should be running; null while it follows its channel.
   */
  targetId: string | null;
}

export interface DeviceSettings {
  vpdLeafOffsetDay: number;
  vpdLeafOffsetNight: number;
  ppfdLuxFactor: number;
}

export interface DeviceState {
  /**
   * Last sample or status; what `offline` is decided from.
   */
  lastSeenAt: string | null;
  claimedAt: string | null;
  /**
   * What the device reports it is running, which is the build uuid.
   */
  firmwareId: string | null;
  updateStartedAt: string | null;
  updateEndedAt: string | null;
  /**
   * The device suppresses its own alarms until then; the cloud's are silenced separately.
   */
  maintenanceUntil: string | null;
  /**
   * The raw `hardware-info` report, flat as the device sends it.
   */
  hardware: {
    [k: string]: string;
  };
  socketStateChangedAt: {
    [k: string]: string;
  };
  socketsReportedAt: string | null;
}

export interface Device {
  /**
   * The id the firmware was provisioned with.
   */
  id: string;
  createdAt: string;
  type: string;
  /**
   * The update class; null until a firmware has been built for this device.
   */
  classId: string | null;
  serialNumber: number | null;
  /**
   * null while the device is unclaimed and claimable.
   */
  ownerId: string | null;
  spaceId: string | null;
  name: string | null;
  firmware: DeviceFirmwareTarget;
  /**
   * null before the device has reported one.
   */
  configuration: DeviceConfiguration | null;
  settings: DeviceSettings;
  isDemo: boolean;
  state: DeviceState;
}

export interface DevicePage {
  items: Device[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface DeviceUpdate {
  name?: string | null;
  spaceId?: string | null;
  firmware?: DeviceFirmwareTarget;
  settings?: DeviceSettings;
}

export interface DeviceConfigurationEnvelope {
  configuration: DeviceConfiguration;
}

export interface AdminDeviceCreate {
  /**
   * The id the firmware was provisioned with.
   */
  id: string;
  type: string;
  /**
   * The update class; null until a firmware has been built for this device.
   */
  classId: string | null;
  serialNumber: number | null;
}

export interface DeviceClassFirmwareIds {
  stable: string | null;
  beta: string | null;
  alpha: string | null;
}

export interface DeviceClassRollout {
  paused: boolean;
  percent: number;
}

export interface DeviceClass {
  id: string;
  createdAt: string;
  name: string;
  description: string | null;
  /**
   * How many devices of the class may be updating at once.
   */
  concurrentUpdates: number;
  /**
   * Failed updates after which the rollout stops by itself.
   */
  maxFailures: number;
  firmwareIds: DeviceClassFirmwareIds;
  rollout: DeviceClassRollout;
}

export interface DeviceClassPage {
  items: DeviceClass[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface DeviceClassCreate {
  name: string;
  description: string | null;
  /**
   * How many devices of the class may be updating at once.
   */
  concurrentUpdates: number;
  /**
   * Failed updates after which the rollout stops by itself.
   */
  maxFailures: number;
  firmwareIds: DeviceClassFirmwareIds;
  rollout: DeviceClassRollout;
}

export interface DeviceClassUpdate {
  name?: string;
  description?: string | null;
  /**
   * How many devices of the class may be updating at once.
   */
  concurrentUpdates?: number;
  /**
   * Failed updates after which the rollout stops by itself.
   */
  maxFailures?: number;
  firmwareIds?: DeviceClassFirmwareIds;
  rollout?: DeviceClassRollout;
}

export interface Firmware {
  id: string;
  createdAt: string;
  classId: string;
  name: string | null;
  /**
   * The build's uuid; builds are not ordered and cannot be compared.
   */
  version: string;
  /**
   * Once true it stays true, so a build can be rolled back to knowingly.
   */
  wasStable: boolean;
}

export interface FirmwarePage {
  items: Firmware[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface FirmwareCreate {
  classId: string;
  name: string | null;
  /**
   * The build's uuid; builds are not ordered and cannot be compared.
   */
  version: string;
}

export interface FirmwareUpdate {
  classId?: string;
  name?: string | null;
  /**
   * The build's uuid; builds are not ordered and cannot be compared.
   */
  version?: string;
}

export interface FirmwareBinary {
  id: string;
  createdAt: string;
  firmwareId: string;
  /**
   * The file the device asks for by name.
   */
  name: string;
  data: Buffer;
}

export interface FirmwareBinaryUpload {
  data: Buffer;
}

export interface ClaimCode {
  id: string;
  createdAt: string;
  code: string;
  deviceId: string;
}

export interface DeviceClaimCreate {
  code: string;
  /**
   * Absent names the device after its type.
   */
  name?: string;
  spaceId?: string;
}

export interface DeviceClaimResult {
  device: Device;
  spaceCreated: boolean;
}

export interface SocketOverride {
  state: SocketOverrideState;
  validUntil: string;
}

export interface SocketTimer {
  onSeconds: number;
  everySeconds: number;
}

export interface Socket {
  /**
   * -1 when the device reports no table, in which case its role addresses it.
   */
  slot: number;
  role: SocketRole;
  /**
   * Empty on sockets paired before the firmware kept ids.
   */
  hardwareId: string;
  address: string;
  state: SocketState;
  override: SocketOverride | null;
  timer: SocketTimer | null;
  /**
   * When the row last changed state; null until it has been seen change.
   */
  stateChangedAt: string | null;
}

export interface DeviceCapabilities {
  socketOverride: boolean;
  socketTimer: boolean;
  /**
   * Whether the controller's own light output takes an override.
   */
  lightOverride: boolean;
  /**
   * The roles this build knows; a role outside it is never sent.
   */
  roles: SocketRole[];
  pulseSeconds: {
    [k: string]: number;
  };
}

export interface SocketPage {
  items: Socket[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
  capabilities: DeviceCapabilities;
}

export interface RebootCommand {
  kind: 'reboot';
}

export interface MaintenanceCommand {
  kind: 'maintenance';
  forSeconds: number;
}

export interface TestCommand {
  kind: 'test';
  outputs: {
    [k: string]: number;
  };
}

export interface StopTestCommand {
  kind: 'stop_test';
}

export interface CaptureStillCommand {
  kind: 'capture_still';
}

export interface SocketOverrideCommand {
  kind: 'socket_override';
  subject: {
    type: 'socket' | 'output';
    id: string;
  };
  state: SocketOverrideState;
  /**
   * The override expires after this; a reboot ends it too. Zero only with `auto`, which carries no duration.
   */
  forSeconds: number;
}

export interface SocketCredentials {
  username: string;
  password: string;
}

export interface SocketSetCommand {
  kind: 'socket_set';
  /**
   * null adds a socket to the role instead of configuring one it already has.
   */
  slot: number | null;
  role: SocketRole;
  /**
   * Host or IP the device reaches the socket at, over plain HTTP on the local network.
   */
  address: string;
  credentials: SocketCredentials | null;
  /**
   * Only `pump` and `custom_timer` run on one.
   */
  timer: SocketTimer | null;
}

export interface DeviceCommandResult {
  publishedAt: string;
  /**
   * Whether the device had been heard from inside the offline window when the command went out.
   */
  deviceOnline: boolean;
}

export interface SocketUpdate {
  role: SocketRole;
  /**
   * Host or IP the device reaches the socket at, over plain HTTP on the local network.
   */
  address: string;
  credentials: SocketCredentials | null;
  /**
   * Only `pump` and `custom_timer` run on one.
   */
  timer: SocketTimer | null;
}

export interface SocketOverrideUpdate {
  state: SocketOverrideState;
  /**
   * The override expires after this; a reboot ends it too. Zero only with `auto`, which carries no duration.
   */
  forSeconds: number;
}

export interface SocketTestCreate {
  forSeconds: number;
}

export interface StepDuration {
  value: number;
  unit: DurationUnit;
}

export interface PlanStep {
  /**
   * Stable across edits, so `state.activeStepIndex` survives a step being inserted above it.
   */
  id: string;
  name: string;
  /**
   * The stage this step puts the grow in; null leaves the phase alone.
   */
  stage: GrowthStage | null;
  /**
   * The climate preset applied on top of the stage, such as `late_flowering`.
   */
  preset: string | null;
  duration: StepDuration;
  settings: DeviceConfiguration;
  waitForConfirmation: boolean;
  confirmationMessage: string | null;
}

export interface PlanNotify {
  mode: PlanNotifyMode;
  /**
   * Where the plan writes; null uses the owner's address.
   */
  email: string | null;
  /**
   * Whether a step change also lands in the diary.
   */
  writeEntries: boolean;
}

export interface PlanState {
  status: PlanStatus;
  activeStepIndex: number;
  stepStartedAt: string | null;
  pausedElapsedMs: number;
  pauseReason: string | null;
  /**
   * The engine re-applies the running step hourly.
   */
  lastAppliedAt: string | null;
  /**
   * When the plan's own mail about the waiting step went out, which it does once.
   */
  confirmationNotifiedAt: string | null;
  /**
   * When everybody who keeps the tent had been told the step is waiting; null while the ask is still outstanding.
   */
  confirmationAskedAt: string | null;
  /**
   * When that ask was last attempted; an outstanding ask is attempted again.
   */
  confirmationAskTriedAt: string | null;
}

export interface Plan {
  id: string;
  createdAt: string;
  deviceId: string;
  /**
   * What it was started from; null once it no longer matters.
   */
  templateId: string | null;
  name: string;
  steps: PlanStep[];
  /**
   * Start again at the first step instead of completing.
   */
  loop: boolean;
  notify: PlanNotify;
  state: PlanState;
}

export interface PlanStepInput {
  /**
   * Stable across edits, so `state.activeStepIndex` survives a step being inserted above it.
   */
  id?: string;
  name: string;
  /**
   * The stage this step puts the grow in; null leaves the phase alone.
   */
  stage?: GrowthStage | null;
  /**
   * The climate preset applied on top of the stage, such as `late_flowering`.
   */
  preset?: string | null;
  duration: StepDuration;
  settings: DeviceConfiguration;
  waitForConfirmation: boolean;
  confirmationMessage: string | null;
}

export interface PlanReplace {
  /**
   * What it was started from; null once it no longer matters.
   */
  templateId: string | null;
  name: string;
  /**
   * Start again at the first step instead of completing.
   */
  loop: boolean;
  notify: PlanNotify;
  steps: PlanStepInput[];
}

export interface PlanTemplate {
  id: string;
  createdAt: string;
  ownerId: string;
  name: string;
  isPublic: boolean;
  steps: PlanStep[];
}

export interface PlanTemplatePage {
  items: PlanTemplate[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface PlanTemplateCreate {
  name: string;
  isPublic: boolean;
  steps: PlanStepInput[];
}

export interface PlanTemplateUpdate {
  name?: string;
  isPublic?: boolean;
  steps?: PlanStepInput[];
}

export interface AlarmWebhook {
  method: WebhookMethod;
  headers: {
    [k: string]: string;
  };
  /**
   * Body template sent when the rule triggers.
   */
  triggeredPayload: string;
  resolvedPayload: string;
  /**
   * Whether a failed call is written to the diary.
   */
  reportErrors: boolean;
  /**
   * Call through the device's tunnel, for a target on the local network.
   */
  tunnel: boolean;
}

export interface AlarmDeliveryCustom {
  channel: AlarmDeliveryChannel;
  /**
   * The address or the URL, by channel.
   */
  target: string;
  /**
   * Whether the message carries the reading and the thresholds.
   */
  includeDetails: boolean;
  webhook: AlarmWebhook | null;
}

export interface AlarmDelivery {
  mode: AlarmDeliveryMode;
  custom: AlarmDeliveryCustom | null;
}

export interface ReadingWatch {
  kind: 'reading';
  metric: Metric;
  upper: number | null;
  lower: number | null;
}

export interface OutputLevelWatch {
  kind: 'output_level';
  output: OutputMetric;
  upper: number | null;
  lower: number | null;
}

export interface OutputRunningWatch {
  kind: 'output_running';
  output: OutputMetric;
}

export interface AlarmRuleState {
  triggered: boolean;
  lastTriggeredAt: string | null;
  lastResolvedAt: string | null;
  /**
   * The worst reading of the open episode.
   */
  extremeValue: number | null;
  /**
   * The sample the rule was last evaluated against.
   */
  lastSampleAt: string | null;
}

export interface AlarmRule {
  id: string;
  createdAt: string;
  deviceId: string;
  name: string;
  watch: AlarmWatch;
  /**
   * How long the watch has to be out of bounds before the rule triggers.
   */
  forSeconds: number;
  severity: Severity;
  origin: AlarmOrigin;
  /**
   * The preset that wrote this rule, so applying it again can update it.
   */
  presetId: string | null;
  enabled: boolean;
  /**
   * Silence after a trigger, so one bad hour is not one message a minute.
   */
  cooldownSeconds: number;
  /**
   * How often a rule that stays triggered says so again; 0 never repeats.
   */
  repeatSeconds: number;
  delivery: AlarmDelivery;
  silencedUntil: string | null;
  state: AlarmRuleState;
}

export interface AlarmRulePage {
  items: AlarmRule[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface AlarmRuleCreate {
  name: string;
  watch: AlarmWatch;
  /**
   * How long the watch has to be out of bounds before the rule triggers.
   */
  forSeconds: number;
  severity: Severity;
  enabled: boolean;
  /**
   * Silence after a trigger, so one bad hour is not one message a minute.
   */
  cooldownSeconds: number;
  /**
   * How often a rule that stays triggered says so again; 0 never repeats.
   */
  repeatSeconds: number;
  delivery: AlarmDelivery;
}

export interface AlarmRuleUpdate {
  name?: string;
  watch?: AlarmWatch;
  /**
   * How long the watch has to be out of bounds before the rule triggers.
   */
  forSeconds?: number;
  severity?: Severity;
  enabled?: boolean;
  /**
   * Silence after a trigger, so one bad hour is not one message a minute.
   */
  cooldownSeconds?: number;
  /**
   * How often a rule that stays triggered says so again; 0 never repeats.
   */
  repeatSeconds?: number;
  delivery?: AlarmDelivery;
}

export interface AlarmSilence {
  forSeconds: number;
}

export interface Alert {
  id: string;
  createdAt: string;
  /**
   * null for an alert the health loop raised without a rule.
   */
  ruleId: string | null;
  deviceId: string | null;
  cameraId: string | null;
  spaceId: string | null;
  kind: AlertKind;
  severity: Severity;
  startedAt: string;
  resolvedAt: string | null;
  /**
   * The reading that triggered it.
   */
  value: number | null;
  /**
   * The worst reading while it was open.
   */
  extremeValue: number | null;
}

export interface AlertPage {
  items: Alert[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface Setpoints {
  day: {
    [k: string]: number;
  };
  night: {
    [k: string]: number;
  };
  /**
   * Which half of the cycle the device says it is in.
   */
  active: 'day' | 'night';
}

export interface DeviceLive {
  deviceId: string;
  metrics: {
    [k: string]: MetricValue;
  };
  /**
   * null for a device that holds no targets, such as a plug.
   */
  setpoints: Setpoints | null;
}

export interface MetricSeries {
  metric: Metric;
  points: SeriesPoint[];
}

export interface OutputSeries {
  output: OutputMetric;
  points: SeriesPoint[];
}

export interface SeriesQuery {
  metrics: Metric[];
  outputs?: OutputMetric[];
  startsAt: string;
  endsAt: string;
  /**
   * The window each point summarises.
   */
  stepSeconds?: number;
}

export interface DeviceSeries {
  deviceId: string;
  startsAt: string;
  endsAt: string;
  stepSeconds: number;
  metrics: MetricSeries[];
  outputs: OutputSeries[];
}

export interface FleetFirmwareStats {
  firmwareId: string | null;
  version: string;
  name: string | null;
  total: number;
  online: number;
  updating: number;
  failed: number;
  /**
   * null until an update to this build has finished.
   */
  averageUpdateMs: number | null;
  maxUpdateMs: number | null;
}

export interface FleetClass {
  classId: string;
  name: string;
  total: number;
  /**
   * Heard from inside the offline window.
   */
  online: number;
  rollout: DeviceClassRollout;
  firmwares: FleetFirmwareStats[];
}

export interface Fleet {
  classes: FleetClass[];
  /**
   * Devices whose type has no class yet, so no rollout reaches them.
   */
  unclassifiedDevices: number;
}

export interface AdminUserStats {
  total: number;
  active: number;
  admins: number;
}

export interface AdminDeviceStats {
  total: number;
  claimed: number;
  online: number;
  updating: number;
}

export interface AdminCameraStats {
  total: number;
  /**
   * Cameras whose entitlement has not run out, whatever granted it.
   */
  entitled: number;
  /**
   * Cameras that have stopped delivering stills.
   */
  stale: number;
}

export interface AdminContentStats {
  spaces: number;
  grows: number;
  publicGrows: number;
  plants: number;
  entries: number;
  media: number;
  /**
   * What the picture bucket holds, which is nearly all of the disk.
   */
  mediaBytes: number;
}

export interface AdminStats {
  collectedAt: string;
  users: AdminUserStats;
  devices: AdminDeviceStats;
  cameras: AdminCameraStats;
  content: AdminContentStats;
}

export interface AdminLogLine {
  /**
   * What the list is paged by; the log is the process's own and not a collection of this model.
   */
  id: string;
  loggedAt: string;
  level: AdminLogLevel;
  context: string;
  message: string;
  deviceId: string | null;
  userId: string | null;
}

export interface AdminLogPage {
  items: AdminLogLine[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface SpaceRetention {
  /**
   * How long raw climate points are kept; null is the install default.
   */
  climateDays: number | null;
}

export interface Space {
  id: string;
  ownerId: string;
  /**
   * The most this account may do here. It is about the reader, so two people reading the same space are answered differently.
   */
  youMay: 'own' | 'manage' | 'log' | 'view';
  kind: SpaceKind;
  name: string;
  /**
   * A space of kind `room`, one level deep. Null is a space that stands on its own.
   */
  roomId: string | null;
  presetPrompt: PresetPrompt;
  retention: SpaceRetention;
  isDemo: boolean;
  /**
   * A tombstone: history still names the space, so it is kept and no longer listed.
   */
  archivedAt: string | null;
  createdAt: string;
}

export interface Membership {
  id: string;
  spaceId: string;
  userId: string;
  role: MemberRole;
  invitedBy: string | null;
  /**
   * The invite that was redeemed, or null for a member added by hand.
   */
  inviteId: string | null;
  createdAt: string;
}

export interface InviteState {
  useCount: number;
  lastUsedAt: string | null;
}

export interface Invite {
  id: string;
  /**
   * 8 characters from the claim-code alphabet; unique.
   */
  code: string;
  spaceId: string;
  role: MemberRole;
  createdBy: string;
  expiresAt: string | null;
  revokedAt: string | null;
  state: InviteState;
  createdAt: string;
}

export interface ClimateTargets {
  temperature: number | null;
  humidity: number | null;
}

export interface PhaseTargets {
  day: ClimateTargets;
  night: ClimateTargets;
  /**
   * One target: the controller only raises CO2 while the light is on.
   */
  co2: number | null;
}

export interface Phase {
  id: string;
  stage: GrowthStage;
  preset: string | null;
  startedAt: string;
  source: PhaseSource;
  /**
   * Null is every plant of the grow; a list is the scope of a split.
   */
  plantIds: string[] | null;
  /**
   * The controller the targets were read from, if any.
   */
  deviceId: string | null;
  /**
   * A snapshot: Influx stores sensors and outputs, never setpoints, so a past phase has no other way to draw its target band.
   */
  targets: PhaseTargets | null;
  /**
   * The user, or null when a plan or a preset wrote the phase.
   */
  setBy: string | null;
}

export interface Placement {
  id: string;
  /**
   * Null is "no fixed place".
   */
  spaceId: string | null;
  startedAt: string;
  /**
   * Null is open: this is where the plants are now.
   */
  endedAt: string | null;
  /**
   * Null is every plant of the grow.
   */
  plantIds: string[] | null;
}

export interface GrowScheme {
  origin: GrowSchemeOrigin;
  /**
   * Multiplier on the printed amounts; 1 is the scheme as published.
   */
  strength: number;
  /**
   * The tap water's own EC, which the scheme's figures are read on top of.
   */
  waterEc: number | null;
  /**
   * The scheme's own selector, such as its medium or plant type; the server does not interpret it.
   */
  plantType: string;
  /**
   * The week the light is flipped; null for an autoflower.
   */
  flipWeek: number | null;
  /**
   * The grid was changed by hand and no longer matches its origin.
   */
  edited: boolean;
  grid: SchemeWeek[];
}

export interface MeasurementDefinition {
  key: string;
  name: string;
  unit: string;
  /**
   * A reading is taken per plant rather than for the grow.
   */
  perPlant: boolean;
  /**
   * The low end of the band aimed at; null where the target is open below.
   */
  targetMin: number | null;
  /**
   * The high end; null where it is open above. Both null is a measurement with no target.
   */
  targetMax: number | null;
  /**
   * Drawn as a series beside the climate charts.
   */
  chart: boolean;
}

export interface Grow {
  id: string;
  ownerId: string;
  name: string;
  description: string | null;
  type: GrowType;
  /**
   * Ordered by `startedAt`. The single truth for the day counter, the phase and the "auto" tag.
   */
  phases: Phase[];
  placements: Placement[];
  scheme: GrowScheme | null;
  measurements: MeasurementDefinition[];
  visibility: GrowVisibility;
  /**
   * Unique and stable, assigned at creation, so making a grow public never changes its address.
   */
  slug: string;
  coverMediaId: string | null;
  /**
   * The whole-grow timelapse, once it has been rendered.
   */
  filmMediaId: string | null;
  startedAt: string;
  endedAt: string | null;
  isDemo: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PlantHarvest {
  harvestedAt: string;
  wetWeightG: number | null;
  dryWeightG: number | null;
}

export interface Plant {
  id: string;
  growId: string;
  strain: string;
  /**
   * What the plant is called on a card, such as "Amnesia 3".
   */
  label: string;
  status: PlantStatus;
  harvest: PlantHarvest | null;
  createdAt: string;
}

export interface Follow {
  id: string;
  userId: string;
  growId: string;
  createdAt: string;
}

export interface Reminder {
  id: string;
  subject: GrowOrSpaceRef;
  kind: ReminderKind;
  label: string;
  /**
   * A rhythm. Exactly one of `everyDays` and `onceAt` is set.
   */
  everyDays: number | null;
  onceAt: string | null;
  /**
   * Who the derived task is for; null is everyone who may log.
   */
  assigneeId: string | null;
  /**
   * Prefilled entry values for the derived task; null when there are none.
   */
  defaults: any;
  createdBy: string;
  createdAt: string;
}

export interface TaskCompletion {
  entryId: string;
  occurredAt: string;
  authorId: string | null;
}

export interface Task {
  /**
   * Deterministic: the same source and the same due instant always produce the same id, so a completion needs nothing stored beforehand.
   */
  id: string;
  source: TaskSource;
  /**
   * The reminder or plan step it was derived from; null for a task the scheme grid implies.
   */
  sourceId: string | null;
  subject: GrowOrSpaceRef;
  kind: ReminderKind;
  label: string;
  dueAt: string;
  assigneeId: string | null;
  /**
   * Prefilled entry values for the derived task; null when there are none.
   */
  defaults: any;
  done: boolean;
  /**
   * The entry that ticked it off; null while it is still waiting.
   */
  completion: TaskCompletion | null;
}

export interface PhaseGroup {
  stage: GrowthStage;
  preset: string | null;
  phaseDay: number;
  plantIds: string[];
}

export interface GrowLocation {
  spaceId: string | null;
  plantIds: string[];
}

export interface GrowSummary {
  /**
   * 1 on the day the first phase started, counted to `endedAt` once the grow has ended; null before the first phase.
   */
  dayNumber: number | null;
  /**
   * The stage of the largest group of plants.
   */
  stage: GrowthStage | null;
  preset: string | null;
  phaseDay: number | null;
  /**
   * Counted like `dayNumber`, so it lines up with the feeding scheme's grid.
   */
  weekNumber: number | null;
  /**
   * The phase was set by a preset or by the plan rather than by hand.
   */
  isAuto: boolean;
  /**
   * Empty while every plant shares the headline phase; otherwise every group, that one included.
   */
  groups: PhaseGroup[];
  locations: GrowLocation[];
}

export interface GrowListItem {
  id: string;
  ownerId: string;
  name: string;
  description: string | null;
  type: GrowType;
  /**
   * Ordered by `startedAt`. The single truth for the day counter, the phase and the "auto" tag.
   */
  phases: Phase[];
  placements: Placement[];
  scheme: GrowScheme | null;
  measurements: MeasurementDefinition[];
  visibility: GrowVisibility;
  /**
   * Unique and stable, assigned at creation, so making a grow public never changes its address.
   */
  slug: string;
  coverMediaId: string | null;
  /**
   * The whole-grow timelapse, once it has been rendered.
   */
  filmMediaId: string | null;
  startedAt: string;
  endedAt: string | null;
  isDemo: boolean;
  createdAt: string;
  updatedAt: string;
  summary: GrowSummary;
}

export interface SpaceCreate {
  kind: SpaceKind;
  name: string;
  /**
   * A space of kind `room`, one level deep. Null is a space that stands on its own.
   */
  roomId?: string | null;
  presetPrompt?: PresetPrompt;
  retention?: SpaceRetention;
}

export interface SpaceUpdate {
  kind?: SpaceKind;
  name?: string;
  /**
   * A space of kind `room`, one level deep. Null is a space that stands on its own.
   */
  roomId?: string | null;
  presetPrompt?: PresetPrompt;
  retention?: SpaceRetention;
}

export interface DevicePlacement {
  deviceId: string;
  /**
   * The space the device now stands in; null once it has been taken out.
   */
  spaceId: string | null;
}

export interface PresetApplicationCreate {
  stage: GrowthStage;
  /**
   * Absent or null applies the stage's own targets with no preset on top.
   */
  preset?: string | null;
  decision?: GrowDecision;
  /**
   * The grow to move here.
   */
  growId?: string;
}

export interface PresetApplication {
  spaceId: string;
  stage: GrowthStage;
  preset: string | null;
  appliedAt: string;
  /**
   * The controllers the targets were written to; empty in a space that has none.
   */
  deviceIds: string[];
  /**
   * The grow whose phase was set; null when only the climate was applied.
   */
  growId: string | null;
  phaseId: string | null;
  /**
   * No open grow was found here, so no phase was written and the client asks what to do about it.
   */
  growDecisionNeeded: boolean;
  decisions: GrowDecision[];
  planEffect: PresetPlanEffect;
}

export interface MembershipCreate {
  handle: string;
  role: MemberRole;
}

export interface MembershipUpdate {
  role: MemberRole;
}

export interface InviteCreate {
  role: MemberRole;
  expiresAt?: string | null;
}

export interface InvitePreview {
  /**
   * The only field a dead code answers. Which of revoked, expired, archived or never-issued it was is not said, because the route is open.
   */
  isValid: boolean;
  spaceName: string | null;
  spaceKind: SpaceKind | null;
  role: MemberRole | null;
  invitedByHandle: string | null;
  expiresAt: string | null;
}

export interface InviteAcceptance {
  membership: Membership;
  space: Space;
}

export interface PlantBatch {
  strain: string;
  count: number;
}

export interface GrowCreate {
  name: string;
  description?: string | null;
  type: GrowType;
  /**
   * Defaults to now.
   */
  startedAt?: string;
  /**
   * The opening placement; absent or null is "no fixed place".
   */
  spaceId?: string | null;
  plants: PlantBatch[];
  scheme?: GrowScheme | null;
  measurements?: MeasurementDefinition[];
  visibility?: GrowVisibility;
}

export interface PhaseCreate {
  stage: GrowthStage;
  preset?: string | null;
  /**
   * Defaults to now.
   */
  startedAt?: string;
  /**
   * Absent or null is every plant.
   */
  plantIds?: string[] | null;
}

export interface PlacementCreate {
  /**
   * Null moves the plants to no fixed place.
   */
  spaceId: string | null;
  /**
   * Defaults to now.
   */
  startedAt?: string;
  /**
   * Absent or null is every plant.
   */
  plantIds?: string[] | null;
}

export interface HarvestCreate {
  /**
   * Absent or null harvests every active plant; a list is a split harvest.
   */
  plantIds?: string[] | null;
  /**
   * Defaults to now.
   */
  harvestedAt?: string;
  wetWeightG?: number | null;
  dryWeightG?: number | null;
}

export interface HarvestResult {
  /**
   * The plants as they now stand, weights included.
   */
  plants: Plant[];
  entryId: string;
}

export interface SplitCreate {
  /**
   * @minItems 1
   */
  plantIds: [string, ...string[]];
  /**
   * Defaults to now.
   */
  startedAt?: string;
  stage?: GrowthStage;
  preset?: string | null;
  spaceId?: string | null;
}

export interface SplitResult {
  plantIds: string[];
  phase: Phase | null;
  placement: Placement | null;
}

export interface GrowUpdate {
  name?: string;
  description?: string | null;
  type?: GrowType;
  scheme?: GrowScheme | null;
  measurements?: MeasurementDefinition[];
  visibility?: GrowVisibility;
  coverMediaId?: string | null;
  startedAt?: string;
  endedAt?: string | null;
}

export interface PlantCreate {
  strain: string;
  /**
   * What the plant is called on a card, such as "Amnesia 3".
   */
  label?: string;
}

export interface PlantUpdate {
  strain?: string;
  /**
   * What the plant is called on a card, such as "Amnesia 3".
   */
  label?: string;
  status?: PlantStatus;
  harvest?: PlantHarvest | null;
}

export interface PhaseUpdate {
  stage?: GrowthStage;
  preset?: string | null;
  /**
   * Defaults to now.
   */
  startedAt?: string;
  /**
   * Absent or null is every plant.
   */
  plantIds?: string[] | null;
}

export interface PlacementUpdate {
  /**
   * Null is "no fixed place".
   */
  spaceId?: string | null;
  startedAt?: string;
  /**
   * Null is open: this is where the plants are now.
   */
  endedAt?: string | null;
  /**
   * Null is every plant of the grow.
   */
  plantIds?: string[] | null;
}

export interface ReminderCreate {
  subject: GrowOrSpaceRef;
  kind: ReminderKind;
  label: string;
  /**
   * A rhythm. Exactly one of `everyDays` and `onceAt` is set.
   */
  everyDays: number | null;
  onceAt: string | null;
  /**
   * Who the derived task is for; null is everyone who may log.
   */
  assigneeId?: string | null;
  /**
   * Prefilled entry values for the derived task; null when there are none.
   */
  defaults?: any;
}

export interface ReminderUpdate {
  subject?: GrowOrSpaceRef;
  kind?: ReminderKind;
  label?: string;
  /**
   * A rhythm. Exactly one of `everyDays` and `onceAt` is set.
   */
  everyDays?: number | null;
  onceAt?: string | null;
  /**
   * Who the derived task is for; null is everyone who may log.
   */
  assigneeId?: string | null;
  /**
   * Prefilled entry values for the derived task; null when there are none.
   */
  defaults?: any;
}

export interface TaskCompletionCreate {
  /**
   * Defaults to now.
   */
  occurredAt?: string;
  text?: string | null;
  /**
   * Absent or null is every plant the task is about.
   */
  plantIds?: string[] | null;
  /**
   * The entry's values for this kind; absent takes the task's `defaults`.
   */
  values?: any;
}

export interface SpacePage {
  items: Space[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface MembershipPage {
  items: Membership[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
  people: Person[];
  room: {
    id: string;
    name: string;
  } | null;
}

export interface InvitePage {
  items: Invite[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface GrowPage {
  items: GrowListItem[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface PlantPage {
  items: Plant[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface FollowPage {
  items: Follow[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface ReminderPage {
  items: Reminder[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface TaskPage {
  items: Task[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface EntryReading {
  key: string;
  value: number;
  plantId: string | null;
}

export interface EntryDose {
  productKey: string;
  name: string;
  amount: number;
  /**
   * The unit of `amount`, such as `ml`: the scheme's own `ml/l` with the per-litre taken off.
   */
  unit: string;
}

export interface MeasurementEntryValues {
  kind: 'measurement';
  readings: EntryReading[];
}

export interface WaterEntryValues {
  kind: 'water';
  litres: number | null;
  readings: EntryReading[];
}

export interface FeedEntryValues {
  kind: 'feed';
  litres: number | null;
  /**
   * The row of the grid the doses were read from; null when the grow feeds without a scheme.
   */
  schemeWeek: number | null;
  doses: EntryDose[];
  readings: EntryReading[];
}

export interface PhotoEntryValues {
  kind: 'photo';
}

export interface NoteEntryValues {
  kind: 'note';
}

export interface TrainingEntryValues {
  kind: 'training';
}

export interface VisitEntryValues {
  kind: 'visit';
}

export interface SystemEntryValues {
  kind: 'system';
}

export interface AlarmEntryValues {
  kind: 'alarm';
}

export interface PhaseEntryValues {
  kind: 'phase';
  phaseId: string;
  stage: GrowthStage;
  /**
   * The climate preset applied with the stage, such as `late_flowering`.
   */
  preset: string | null;
}

export interface MoveEntryValues {
  kind: 'move';
  placementId: string;
  /**
   * Where the plants moved to; null is "no fixed place".
   */
  spaceId: string | null;
}

export interface HarvestEntryValues {
  kind: 'harvest';
  wetWeightG: number | null;
  dryWeightG: number | null;
}

export interface PlanEntryValues {
  kind: 'plan';
  planId: string;
  stepIndex: number;
  /**
   * The transition that caused the entry; null when the engine simply moved on to the next step.
   */
  transition: PlanTransitionKind | null;
}

export interface EntryMessage {
  key: string;
  params: string[];
}

export interface Entry {
  id: string;
  createdAt: string;
  kind: EntryKind;
  /**
   * When the thing happened, which is not when it was written down.
   */
  occurredAt: string;
  source: EntrySource;
  /**
   * Null for what a device, the plan engine or an alarm wrote.
   */
  authorId: string | null;
  growId: string | null;
  spaceId: string | null;
  deviceId: string | null;
  plantIds: string[];
  cameraId: string | null;
  /**
   * The derived task this entry completes; task ids are deterministic, not stored.
   */
  taskId: string | null;
  alertId: string | null;
  severity: Severity | null;
  /**
   * What a human wrote.
   */
  text: string | null;
  message: EntryMessage | null;
  values: EntryValues;
  mediaIds: string[];
  /**
   * Until when the author may still take the entry back.
   */
  undoUntil: string | null;
}

export interface EntryPage {
  items: Entry[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface EntryCreate {
  /**
   * When the thing happened, which is not when it was written down.
   */
  occurredAt?: string;
  growId?: string | null;
  spaceId?: string | null;
  deviceId?: string | null;
  plantIds?: string[];
  cameraId?: string | null;
  /**
   * The derived task this entry completes; task ids are deterministic, not stored.
   */
  taskId?: string | null;
  /**
   * What a human wrote.
   */
  text?: string | null;
  mediaIds?: string[];
  kind: HumanEntryKind;
  values: EntryValuesDraft;
}

export interface EntryUpdate {
  /**
   * When the thing happened, which is not when it was written down.
   */
  occurredAt?: string;
  growId?: string | null;
  spaceId?: string | null;
  deviceId?: string | null;
  plantIds?: string[];
  cameraId?: string | null;
  /**
   * The derived task this entry completes; task ids are deterministic, not stored.
   */
  taskId?: string | null;
  /**
   * What a human wrote.
   */
  text?: string | null;
  mediaIds?: string[];
  values?: EntryValuesDraft;
}

export interface MediaOverlays {
  dayCounter: boolean;
  /**
   * The temperature and humidity of the span, with a cursor on the frame´s own instant.
   */
  climate: boolean;
  /**
   * The diary lines of the span, each as a caption on the frames around it.
   */
  entries: boolean;
}

export interface MediaRender {
  status: MediaRenderStatus;
  framesPerSecond: number;
  watermark: boolean;
  aspect: MediaAspect;
  overlays: MediaOverlays;
  /**
   * Whether the frames taken while the light was off are in the film.
   */
  includeLightsOff: boolean;
  /**
   * The camera shown beside the first one; null for a film of one camera.
   */
  secondCameraId: string | null;
  startedAt: string | null;
  endedAt: string | null;
  error: string | null;
}

export interface MediaExportJob {
  status: MediaRenderStatus;
  scope: ExportScope;
  /**
   * The grow this is an export of; null for an export of the whole account.
   */
  growId: string | null;
  startedAt: string | null;
  endedAt: string | null;
  error: string | null;
}

export interface Media {
  id: string;
  createdAt: string;
  kind: MediaKind;
  mime: string;
  /**
   * Size of the stored file.
   */
  bytes: number;
  cameraId: string | null;
  growId: string | null;
  spaceId: string | null;
  /**
   * Null for what a camera delivered or the composer rendered.
   */
  uploadedBy: string | null;
  capturedAt: string;
  /**
   * The end of the span a film covers; null for a single picture.
   */
  endsAt: string | null;
  window: MediaWindow | null;
  quality: MediaQuality | null;
  lengthSeconds: number | null;
  render: MediaRender | null;
  /**
   * Set on an `export` row and on nothing else; it is what the export is polled by.
   */
  exportJob: MediaExportJob | null;
}

export interface ExportAccepted {
  media: Media;
  queued: boolean;
}

export interface MediaPage {
  items: Media[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface MediaUpload {
  growId?: string | null;
  spaceId?: string | null;
  capturedAt?: string;
  kind: UploadMediaKind;
}

export interface CameraEntitlement {
  validUntil: string | null;
  grant: GrantKind | null;
  tier: EntitlementTier;
  renewalVisible: boolean;
}

export interface CameraEntitlementUpdate {
  validUntil: string | null;
  grant: GrantKind | null;
}

export interface CameraState {
  lastStillAt: string | null;
  lastError: string | null;
  firmwareVersion: string | null;
}

export interface Camera {
  id: string;
  createdAt: string;
  ownerId: string;
  kind: CameraKind;
  /**
   * The controller that answers for this camera; null for one the cloud reaches itself.
   */
  deviceId: string | null;
  spaceId: string | null;
  name: string;
  /**
   * What it is pointed at, as a label beside the picture.
   */
  looksAt: string | null;
  plantIds: string[];
  /**
   * A Terp Cam’s P2P device id.
   */
  did: string | null;
  uid: string | null;
  /**
   * Last address on the local network, as the controller reported it.
   */
  ip: string | null;
  /**
   * The stream URL with its credentials removed.
   */
  url: string | null;
  transport: CameraTransport | null;
  /**
   * Pull the stream through the controller’s tunnel rather than reaching it directly.
   */
  tunnel: boolean;
  model: CameraModel | null;
  stillIntervalSeconds: number;
  nightOff: boolean;
  maintenanceOff: boolean;
  logErrors: boolean;
  /**
   * Warn when this camera stops delivering pictures. On unless it is turned off, which is what makes it opt-out.
   */
  staleWarning: boolean;
  entitlement: CameraEntitlement;
  isDemo: boolean;
  /**
   * A removed camera is a tombstone, so its pictures keep their link.
   */
  removedAt: string | null;
  state: CameraState;
}

export interface CameraPage {
  items: Camera[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface ControllerCameraCreate {
  spaceId?: string | null;
  name: string;
  /**
   * What it is pointed at, as a label beside the picture.
   */
  looksAt?: string | null;
  plantIds?: string[];
  stillIntervalSeconds?: number;
  nightOff?: boolean;
  maintenanceOff?: boolean;
  logErrors?: boolean;
  /**
   * Warn when this camera stops delivering pictures. On unless it is turned off, which is what makes it opt-out.
   */
  staleWarning?: boolean;
  kind: 'terpcam_controller';
  deviceId: string;
}

export interface StandaloneCameraCreate {
  spaceId?: string | null;
  name: string;
  /**
   * What it is pointed at, as a label beside the picture.
   */
  looksAt?: string | null;
  plantIds?: string[];
  stillIntervalSeconds?: number;
  nightOff?: boolean;
  maintenanceOff?: boolean;
  logErrors?: boolean;
  /**
   * Warn when this camera stops delivering pictures. On unless it is turned off, which is what makes it opt-out.
   */
  staleWarning?: boolean;
  kind: 'terpcam_standalone';
  did: string;
}

export interface RtspCameraCreate {
  spaceId?: string | null;
  name: string;
  /**
   * What it is pointed at, as a label beside the picture.
   */
  looksAt?: string | null;
  plantIds?: string[];
  stillIntervalSeconds?: number;
  nightOff?: boolean;
  maintenanceOff?: boolean;
  logErrors?: boolean;
  /**
   * Warn when this camera stops delivering pictures. On unless it is turned off, which is what makes it opt-out.
   */
  staleWarning?: boolean;
  transport?: CameraTransport | null;
  /**
   * Pull the stream through the controller’s tunnel rather than reaching it directly.
   */
  tunnel?: boolean;
  model?: CameraModel | null;
  kind: 'rtsp';
  /**
   * The controller whose tunnel the stream is pulled through; absent or null is one the cloud reaches itself.
   */
  deviceId?: string | null;
  /**
   * The whole stream URL, credentials included.
   */
  url: string;
}

export interface CameraUpdate {
  spaceId?: string | null;
  name?: string;
  /**
   * What it is pointed at, as a label beside the picture.
   */
  looksAt?: string | null;
  plantIds?: string[];
  stillIntervalSeconds?: number;
  nightOff?: boolean;
  maintenanceOff?: boolean;
  logErrors?: boolean;
  /**
   * Warn when this camera stops delivering pictures. On unless it is turned off, which is what makes it opt-out.
   */
  staleWarning?: boolean;
  transport?: CameraTransport | null;
  /**
   * Pull the stream through the controller’s tunnel rather than reaching it directly.
   */
  tunnel?: boolean;
  model?: CameraModel | null;
  /**
   * The controller whose tunnel the stream is pulled through; absent or null is one the cloud reaches itself.
   */
  deviceId?: string | null;
  /**
   * The whole stream URL, credentials included.
   */
  url?: string;
}

export interface TestCaptureAnswer {
  succeeded: boolean;
  mediaId: string | null;
  capturedAt: string | null;
  error: string | null;
}

export interface TimelapseCreate {
  window: MediaWindow;
  /**
   * Defaults to the most recent complete window.
   */
  startsAt?: string;
  /**
   * Read by `phase`, `grow` and `custom`, each of which needs both ends.
   */
  endsAt?: string;
  /**
   * `hd` needs entitlement and is refused without it rather than quietly made `sd`.
   */
  quality?: 'sd' | 'hd';
  framesPerSecond?: number;
  /**
   * A second camera of the same tent, shown beside the first one.
   */
  secondCameraId?: string;
  overlays?: {
    dayCounter?: boolean;
    /**
     * The temperature and humidity of the span, with a cursor on the frame´s own instant.
     */
    climate?: boolean;
    /**
     * The diary lines of the span, each as a caption on the frames around it.
     */
    entries?: boolean;
  };
  /**
   * Defaults to leaving the frames taken in the dark out.
   */
  includeLightsOff?: boolean;
  aspect?: MediaAspect;
}

export interface TimelapseAccepted {
  media: Media;
  queued: boolean;
}

export interface SchemeOrigin {
  assetId: string | null;
  version: string | null;
}

export interface Scheme {
  id: string;
  createdAt: string;
  ownerId: string;
  name: string;
  origin: SchemeOrigin;
  grid: SchemeWeek[];
}

export interface SchemePage {
  items: Scheme[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface SchemeCreate {
  name: string;
  origin?: SchemeOrigin;
  grid: SchemeWeek[];
}

export interface SchemeUpdate {
  name?: string;
  origin?: SchemeOrigin;
  grid?: SchemeWeek[];
}

export interface TimeRange {
  startsAt: string | null;
  endsAt: string | null;
}

export interface ChartViewDefinition {
  deviceIds: string[];
  growId: string | null;
  metrics: Metric[];
  outputs: OutputMetric[];
  /**
   * Keys of the grow's own measurement definitions. A key the grow no longer defines draws nothing.
   */
  measurements: string[];
  span: ChartViewSpan;
  layout: ChartViewLayout;
  /**
   * Width of one bucket, which is what decides how many points come back.
   */
  intervalSeconds: number;
}

export interface ChartView {
  id: string;
  createdAt: string;
  ownerId: string;
  name: string;
  definition: ChartViewDefinition;
}

export interface ChartViewPage {
  items: ChartView[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface ChartViewCreate {
  name: string;
  definition: ChartViewDefinition;
}

export interface ChartViewUpdate {
  name?: string;
  definition?: ChartViewDefinition;
}

export interface ShareLinkState {
  openCount: number;
  lastOpenedAt: string | null;
}

export interface ShareLink {
  id: string;
  createdAt: string;
  token: string;
  kind: ShareKind;
  subject: GrowOrSpaceRef;
  range: TimeRange;
  /**
   * Camera pictures are only ever visible through a link that includes them.
   */
  includeCameras: boolean;
  createdBy: string;
  expiresAt: string | null;
  revokedAt: string | null;
  state: ShareLinkState;
}

export interface ShareLinkPage {
  items: ShareLink[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface ShareLinkCreate {
  kind: ShareKind;
  subject: GrowOrSpaceRef;
  range?: TimeRange;
  /**
   * Camera pictures are only ever visible through a link that includes them.
   */
  includeCameras?: boolean;
  expiresAt?: string | null;
}

export interface ShareLinkUpdate {
  range?: TimeRange;
  /**
   * Camera pictures are only ever visible through a link that includes them.
   */
  includeCameras?: boolean;
  expiresAt?: string | null;
}

export interface Migration {
  id: string;
  createdAt: string;
  /**
   * Unique; it is what says the migration has already run.
   */
  name: string;
  appliedAt: string;
  durationMs: number;
  stats: {
    [k: string]: number;
  };
}

export interface MigrationPage {
  items: Migration[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
}

export interface CardValue {
  metric: Metric;
  /**
   * null when the device has never reported this metric.
   */
  value: number | null;
  measuredAt: string | null;
  state: ValueState;
}

export interface CardSetpoint {
  metric: Metric;
  value: number | null;
  /**
   * Half the width of the band around the target; null for a metric that has none.
   */
  band: number | null;
}

export interface LatestStill {
  mediaId: string;
  cameraId: string;
  capturedAt: string;
}

export interface CardTrend {
  metric: Metric;
  stepSeconds: number;
  endsAt: string;
  /**
   * One figure per window, oldest first; null where the window holds no sample.
   */
  points: (number | null)[];
}

export interface DueTask {
  id: string;
  kind: ReminderKind;
  label: string;
  dueAt: string;
  subject: GrowOrSpaceRef;
  assigneeId: string | null;
}

export interface OpenAlert {
  alertId: string;
  kind: AlertKind;
  severity: Severity;
  startedAt: string;
  value: number | null;
  /**
   * The reading the rule watches, so "78 % RH" can be said; null for an alert raised without a rule, or by a rule watching an output.
   */
  metric: Metric | null;
}

export interface GrowCardStageGroup {
  stage: GrowthStage;
  /**
   * Null where the owner hides counts.
   */
  plantCount: number | null;
}

export interface GrowCard {
  growId: string;
  name: string;
  type: GrowType;
  dayNumber: number | null;
  /**
   * How many days the grow has stood in its current phase.
   */
  phaseDay: number | null;
  stage: GrowthStage | null;
  preset: string | null;
  /**
   * The phase was set by a preset or the plan rather than by a person.
   */
  isAuto: boolean;
  /**
   * Null where the owner hides counts.
   */
  plantCount: number | null;
  /**
   * Each strain once, in the order it was planted.
   */
  strains: string[];
  coverMediaId: string | null;
  stageGroups: GrowCardStageGroup[];
}

export interface HomeSpaceCard {
  /**
   * Null is “no fixed place”: the card stands for the grow alone.
   */
  spaceId: string | null;
  /**
   * The place’s name, or the grow’s own where the card stands for no place.
   */
  name: string;
  /**
   * Null where there is no place, and so no kind of one.
   */
  kind: SpaceKind | null;
  roomId: string | null;
  deviceIds: string[];
  values: CardValue[];
  setpoints: CardSetpoint[];
  /**
   * The last 24 hours of temperature, from the first device in the space that has any.
   */
  trend: CardTrend | null;
  grow: GrowCard | null;
  /**
   * The grow’s newest entries, newest first.
   */
  entries: Entry[];
  latestStill: LatestStill | null;
  dueTasks: DueTask[];
  openAlerts: OpenAlert[];
}

export interface FollowedGrowCard {
  growId: string;
  slug: string;
  name: string;
  /**
   * The owner’s handle, the only name others ever see.
   */
  handle: string;
  dayNumber: number | null;
  stage: GrowthStage | null;
  coverMediaId: string | null;
  updatedAt: string;
}

export interface HomeAnswer {
  spaces: HomeSpaceCard[];
  followedGrows: FollowedGrowCard[];
  /**
   * Everyone the cards name, so a card can say who wrote an entry without another read.
   */
  people: Person[];
}

export interface TargetBand {
  low: number;
  high: number;
}

export interface ClimateExcursion {
  startedAt: string;
  endedAt: string | null;
  /**
   * Which edge it left over: true is above the band.
   */
  above: boolean;
  /**
   * The furthest the reading got while it was out.
   */
  extremeValue: number | null;
}

export interface ClimateVerdictMetric {
  metric: Metric;
  /**
   * Null where nothing here holds a target for this metric, so there is no band to judge it against.
   */
  rating: VerdictRating | null;
  minValue: number | null;
  maxValue: number | null;
  averageValue: number | null;
  dayBand: TargetBand | null;
  /**
   * Null where the metric is not steered in that half at all: CO2 is only raised while the light is on.
   */
  nightBand: TargetBand | null;
  inBandSeconds: number;
  outOfBandSeconds: number;
  /**
   * In the order they happened; empty where the metric has no band.
   */
  excursions: ClimateExcursion[];
}

export interface ActuatorRuns {
  output: OutputMetric;
  runCount: number;
  /**
   * How long it was on altogether, over the windows that held a reading.
   */
  forSeconds: number;
}

export interface ClimateVerdict {
  /**
   * The device the window was read from; null in a space that has none.
   */
  deviceId: string | null;
  startsAt: string;
  endsAt: string;
  forSeconds: number;
  stepSeconds: number;
  rating: VerdictRating | null;
  /**
   * 0 to 1 over every metric that has a band, of the time that was measured; the "91 % in band" of the headline. Null when nothing here is steered.
   */
  inBandFraction: number | null;
  metrics: ClimateVerdictMetric[];
  actuators: ActuatorRuns[];
  /**
   * The same window as a line, coarsened; it comes out of the aggregation that was read anyway.
   */
  trend: CardTrend | null;
}

export interface CameraStill {
  mediaId: string;
  capturedAt: string;
}

export interface OverviewCamera {
  cameraId: string;
  name: string;
  lastStillAt: string | null;
  /**
   * Today's, oldest first and at most one per slot of the day, so the strip spans the day rather than its last few minutes.
   */
  stills: CameraStill[];
}

export interface OverviewGrow {
  growId: string;
  name: string;
  type: GrowType;
  dayNumber: number | null;
  /**
   * How many days the grow has stood in its current phase.
   */
  phaseDay: number | null;
  stage: GrowthStage | null;
  preset: string | null;
  /**
   * The phase was set by a preset or the plan rather than by a person.
   */
  isAuto: boolean;
  /**
   * Null where the owner hides counts.
   */
  plantCount: number | null;
  /**
   * Each strain once, in the order it was planted.
   */
  strains: string[];
  coverMediaId: string | null;
  stageGroups: GrowCardStageGroup[];
  /**
   * Counted like the day counter, so it lines up with the feeding scheme's grid.
   */
  weekNumber: number | null;
  placedAt: string;
  /**
   * The grow’s own day counter on the day these plants arrived here, which is what "here since day 22" says.
   */
  placedOnDay: number | null;
}

export interface OverviewTask {
  id: string;
  kind: ReminderKind;
  label: string;
  dueAt: string;
  subject: GrowOrSpaceRef;
  assigneeId: string | null;
  /**
   * Prefilled entry values for the completion; null when the task prefills nothing.
   */
  defaults: any;
}

export interface OverviewTargets {
  day: CardSetpoint[];
  night: CardSetpoint[];
}

export interface SpaceOverview {
  spaceId: string;
  name: string;
  kind: SpaceKind;
  /**
   * Null where the space stands on its own, and on a shared or public read, which is not told how the place is arranged.
   */
  roomId: string | null;
  /**
   * Null on a shared or public read: what a reader is shown is the tent, not the hardware in it.
   */
  deviceIds: string[] | null;
  /**
   * Empty on a read through a window that has closed, which has no "now" to answer with.
   */
  values: CardValue[];
  setpoints: CardSetpoint[];
  /**
   * Null in a space whose devices hold no targets at all, and on a read through a window that has closed.
   */
  targets: OverviewTargets | null;
  verdict: ClimateVerdict;
  /**
   * Every grow with open plants here, newest first.
   */
  grows: OverviewGrow[];
  cameras: OverviewCamera[];
  /**
   * The newest lines of this space and of the grows standing in it, newest first.
   */
  entries: Entry[];
  dueTasks: OverviewTask[];
  openAlerts: OpenAlert[];
  /**
   * Everyone the answer names, so an entry can say who wrote it without another read.
   */
  people: Person[];
}

export interface SpaceLiveDevice {
  deviceId: string;
  values: CardValue[];
  setpoints: CardSetpoint[];
}

export interface SpaceLiveCamera {
  cameraId: string;
  lastStillAt: string | null;
}

export interface SpaceLive {
  spaceId: string;
  values: CardValue[];
  setpoints: CardSetpoint[];
  devices: SpaceLiveDevice[];
  cameras: SpaceLiveCamera[];
}

export interface TimelineSpan {
  startsAt: string;
  endsAt: string;
}

export interface TimelineTarget {
  setpoint: number;
  band: TargetBand;
}

export interface TimelineTargets {
  startsAt: string;
  endsAt: string;
  /**
   * Null where the targets are the controller's configuration rather than a phase's snapshot.
   */
  phaseId: string | null;
  stage: GrowthStage | null;
  day: TimelineTarget | null;
  /**
   * Null where the metric is not steered in the dark half at all: CO2 is only raised while the light is on.
   */
  night: TimelineTarget | null;
}

export interface TimelinePanel {
  metric: Metric;
  points: SeriesPoint[];
  /**
   * In order, each ending where the next begins; empty where nothing held a target over the window.
   */
  targets: TimelineTargets[];
}

export interface TimelineOutputLane {
  output: OutputMetric;
  /**
   * Two controllers in one tent each drive their own outputs, so a lane names the device it belongs to.
   */
  deviceId: string;
  spans: TimelineSpan[];
}

export interface TimelineAlarm {
  alertId: string;
  kind: AlertKind;
  severity: Severity;
  /**
   * The reading the rule watched; null for an alert the health loop raised without one, or one from a rule watching an output.
   */
  metric: Metric | null;
  startedAt: string;
  endedAt: string | null;
  value: number | null;
  extremeValue: number | null;
}

export interface TimelineCamera {
  cameraId: string;
  name: string;
  /**
   * Oldest first, at most one per step, so the still above the panels is a lookup rather than a request per position.
   */
  frames: CameraStill[];
}

export interface SpaceTimeline {
  spaceId: string;
  name: string;
  kind: SpaceKind;
  range: TimelineRange;
  /**
   * The grow the bands and the day counter are of; null in a space nothing grows in.
   */
  growId: string | null;
  /**
   * The grow's own day counter at each end of the window, which is the "day 33–34" beside the range chips.
   */
  dayFrom: number | null;
  dayTo: number | null;
  startsAt: string;
  endsAt: string;
  /**
   * The window each point summarises; 0 in a space with no device to read, where there are no points at all.
   */
  stepSeconds: number;
  deviceIds: string[];
  panels: TimelinePanel[];
  /**
   * When the light was off, from the light output rather than from the clock; empty where no device reports one.
   */
  nights: TimelineSpan[];
  alarms: TimelineAlarm[];
  outputs: TimelineOutputLane[];
  /**
   * The rail: the diary of this space and of the grows standing in it, oldest first, as the marks are drawn.
   */
  events: Entry[];
  cameras: TimelineCamera[];
  /**
   * Everyone the rail names, so a mark can say who wrote it without another read.
   */
  people: Person[];
}

export interface WeekClimate {
  metric: Metric;
  minValue: number | null;
  maxValue: number | null;
  averageValue: number | null;
  /**
   * The mean over the windows in which the light was on.
   */
  dayAverage: number | null;
  nightAverage: number | null;
}

export interface GrowWeekDay {
  dayNumber: number;
  startsAt: string;
  mediaId: string | null;
  cameraId: string | null;
  capturedAt: string | null;
}

export interface GrowWeekFeeding {
  amounts: SchemeAmount[];
  plannedCount: number;
}

export interface GrowWeekReading {
  key: string;
  value: number;
  change: number | null;
  measuredAt: string;
}

export interface GrowWeekCard {
  weekNumber: number;
  dayFrom: number;
  dayTo: number;
  startsAt: string;
  endsAt: string;
  stage: GrowthStage | null;
  preset: string | null;
  /**
   * 1 in the week the stage began; null before the first phase.
   */
  stageWeek: number | null;
  /**
   * The controllers the averages were read from. Empty where nothing measures in the places the grow stood, which a card says rather than drawing dashes; null on a shared or public read, where the averages are the diary and the hardware behind them is not.
   */
  deviceIds: string[] | null;
  climate: WeekClimate[];
  /**
   * Hours of light per day over the week, from the controller’s light output.
   */
  lightHours: number | null;
  /**
   * Seven; a day that has not happened yet carries no picture.
   */
  days: GrowWeekDay[];
  /**
   * Null for a grow that is fed no scheme.
   */
  feeding: GrowWeekFeeding | null;
  readings: GrowWeekReading[];
  waterCount: number;
  feedCount: number;
  /**
   * The week’s diary lines, newest first, capped; `entryCount` is how many there are.
   */
  entries: Entry[];
  entryCount: number;
  timelapseMediaId: string | null;
}

export interface GrowWeekCardPage {
  items: GrowWeekCard[];
  /**
   * Pass back as `cursor` for the next page; null on the last one.
   */
  nextCursor: string | null;
  people: Person[];
}

export interface GrowReportPhase {
  phaseId: string;
  stage: GrowthStage;
  preset: string | null;
  startedAt: string;
  endedAt: string | null;
  dayFrom: number;
  /**
   * Null while the phase is the one the grow is in, which is what "→ today" says.
   */
  dayTo: number | null;
  dayCount: number;
  /**
   * Where the plants stood during it, in the order they arrived; null on a shared or public read, which is told the story and not the address.
   */
  spaceIds: string[] | null;
  /**
   * The still nearest the middle of the phase, which is the chapter’s picture.
   */
  coverMediaId: string | null;
  climate: WeekClimate[];
  /**
   * The share of the phase in which every metric with a target sat inside `TARGET_BAND`; null where nothing held a target.
   */
  inBandPercent: number | null;
  waterCount: number;
  feedCount: number;
  /**
   * What was done to the plants in this phase, oldest first - "topped d18 · LST d20".
   */
  training: Entry[];
}

export interface GrowHarvest {
  harvestedAt: string | null;
  wetWeightG: number | null;
  dryWeightG: number | null;
}

export interface GrowTotals {
  entryCount: number;
  waterCount: number;
  feedCount: number;
  photoCount: number;
}

export interface GrowReport {
  growId: string;
  name: string;
  description: string | null;
  type: GrowType;
  startedAt: string;
  endedAt: string | null;
  dayCount: number;
  plantCount: number | null;
  strains: string[];
  coverMediaId: string | null;
  filmMediaId: string | null;
  /**
   * Newest first, which is the order the chapters are read in.
   */
  phases: GrowReportPhase[];
  harvest: GrowHarvest | null;
  totals: GrowTotals;
  /**
   * Everyone the chapters name, so an entry can say who wrote it without another read.
   */
  people: Person[];
}

export interface GrowSeriesPoint {
  measuredAt: string;
  value: number;
  /**
   * Null for a reading about the grow rather than about one plant.
   */
  plantId: string | null;
  entryId: string;
}

export interface GrowMeasurementSeries {
  /**
   * Names one of the grow’s `measurements[]`, which is where its name, its unit and its target are.
   */
  key: string;
  points: GrowSeriesPoint[];
}

export interface GrowSeries {
  growId: string;
  range: GrowSeriesRange;
  startsAt: string;
  endsAt: string;
  /**
   * The window each climate and output point summarises; 0 where no device was read at all.
   */
  stepSeconds: number;
  /**
   * The instant day 1 of this grow began, which is what day-of-grow counts from.
   */
  originAt: string;
  dayFrom: number | null;
  dayTo: number | null;
  /**
   * The devices the climate and the outputs were read from: whatever stood where the grow stood.
   */
  deviceIds: string[];
  climate: TimelinePanel[];
  outputs: TimelineOutputLane[];
  /**
   * When the light was off, which is what every panel is shaded by.
   */
  nights: TimelineSpan[];
  measurements: GrowMeasurementSeries[];
}

export interface PublicAuthor {
  handle: string;
  bio: string | null;
  avatarMediaId: string | null;
}

export interface PublicGrowPage {
  slug: string;
  name: string;
  description: string | null;
  type: GrowType;
  author: PublicAuthor;
  startedAt: string;
  endedAt: string | null;
  dayNumber: number | null;
  stage: GrowthStage | null;
  preset: string | null;
  plantCount: number | null;
  strains: string[];
  coverMediaId: string | null;
  filmMediaId: string | null;
  range: TimeRange;
  includeCameras: boolean;
  weeks: GrowWeekCard[];
  harvest: GrowHarvest | null;
  totals: GrowTotals;
}

export interface PublicUserPage {
  author: PublicAuthor;
  grows: FollowedGrowCard[];
}

export interface SharedGrow {
  type: 'grow';
  grow: PublicGrowPage;
}

export interface SharedSpace {
  type: 'space';
  space: SpaceOverview;
}

export interface SharedResolution {
  kind: ShareKind;
  range: TimeRange;
  includeCameras: boolean;
  expiresAt: string | null;
  subject: SharedSubject;
}

export interface LinkCard {
  title: string;
  description: string;
  pageUrl: string;
  /**
   * Absolute URL of the rendered card, for `og:image`.
   */
  imageUrl: string;
  handle: string | null;
  dayNumber: number | null;
  stage: GrowthStage | null;
}
