auth_backends.1 = http
auth_backends.2 = internal
auth_http.http_method   = post
auth_http.user_path     = http://server:8081/mqttauth/@MQTTAUTH_SHARED_SECRET@/user
auth_http.vhost_path    = http://server:8081/mqttauth/@MQTTAUTH_SHARED_SECRET@/vhost
auth_http.resource_path = http://server:8081/mqttauth/@MQTTAUTH_SHARED_SECRET@/resource
auth_http.topic_path    = http://server:8081/mqttauth/@MQTTAUTH_SHARED_SECRET@/topic
mqtt.allow_anonymous = false

