/**
 * Turns the zod schemas in src/schemas.ts into the two things this package
 * publishes: `index.d.ts`, the types every consumer imports, and
 * `openapi-schemas.json`, the API document's `components.schemas`.
 *
 * Both are committed, because consumers link this package with `file:` and no
 * build runs for them. CI regenerates and fails on a diff, the same way it does
 * for lint.
 *
 * The types go out through JSON Schema rather than through `z.infer`, so that
 * what reaches the webapp is a flat declaration file with no dependency on zod
 * at all - the webapp is on TypeScript 4.8, which cannot parse zod's own types.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { z } from 'zod';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

/**
 * The schemas are TypeScript; compile them to a throwaway directory and import
 * that. It has to sit inside the package, or node cannot resolve `zod` from it.
 */
const buildDir = mkdtempSync(join(root, '.generated-'));
mkdirSync(buildDir, { recursive: true });
try {
  execFileSync(
    process.execPath,
    [
      join(root, 'node_modules', 'typescript', 'bin', 'tsc'),
      join(root, 'src', 'schemas.ts'),
      '--outDir',
      buildDir,
      '--module',
      'esnext',
      '--moduleResolution',
      'bundler',
      '--target',
      'es2022',
      '--strict',
    ],
    { stdio: 'inherit' },
  );

  const schemaModule = join(buildDir, 'schemas.js');
  // tsc emits .js; make it loadable as ESM regardless of the package type.
  const mjs = join(buildDir, 'schemas.mjs');
  writeFileSync(mjs, readFileSync(schemaModule, 'utf8'));
  const { registry } = await import(pathToFileURL(mjs).href);

  const { schemas } = z.toJSONSchema(registry, {
    io: 'output',
    // `wireDate` and `wireBytes` describe themselves through `.meta()`; without
    // this, zod refuses a Date or a custom type outright.
    unrepresentable: 'any',
    uri: id => `#/$defs/${id}`,
  });
  for (const schema of Object.values(schemas)) {
    delete schema.$schema;
    delete schema.$id;
  }

  // `tsType` only tells the TypeScript generator below what to emit; it is not a
  // JSON Schema keyword and has no place in a document describing the API.
  const withoutTsTypes = JSON.parse(JSON.stringify(schemas), (key, value) => (key === 'tsType' ? undefined : value));
  writeFileSync(join(root, 'openapi-schemas.json'), `${JSON.stringify(withoutTsTypes, null, 2)}\n`);

  // One document, so every type is emitted and the references between them stay
  // named rather than being inlined.
  const bundle = {
    $defs: schemas,
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(Object.keys(schemas).map(id => [id, { $ref: `#/$defs/${id}` }])),
  };

  const compiled = await compile(bundle, 'EveryType', {
    bannerComment: '',
    declareExternallyReferenced: true,
    enableConstEnums: false,
    style: { singleQuote: true, printWidth: 150 },
  });

  // The root only existed to pull the others in.
  const types = compiled
    .replace(/export interface EveryType \{[^}]*\}\n*/, '')
    .replace(/\n(?=(export|\/\*\*))/g, '\n\n')
    .trim();

  const runtime = readFileSync(join(root, 'src', 'runtime.d.ts'), 'utf8').trim();

  writeFileSync(
    join(root, 'index.d.ts'),
    [
      '// Generated by `npm run generate` from src/schemas.ts and src/runtime.d.ts.',
      '// Do not edit: change the schema and regenerate.',
      '',
      types,
      '',
      runtime,
      '',
    ].join('\n'),
  );

  console.log(`Generated index.d.ts (${Object.keys(schemas).length} types) and openapi-schemas.json`);
} finally {
  rmSync(buildDir, { recursive: true, force: true });
}
