#!/usr/bin/env node
/* eslint-disable */
const fs = require('fs');
const path = require('path');

const ROOT_ENV = path.resolve(__dirname, '..', '..', '.env');
const TARGET = path.resolve(__dirname, '..', 'src', 'environments', 'environment.ts');

function parseEnv(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

const env = parseEnv(ROOT_ENV);
const apiUrl = env.API_URL_EXTERNAL || 'http://localhost:8081';

const contents = `// AUTO-GENERATED by scripts/set-env.js from the root .env file.
// Do not edit by hand — changes will be overwritten on \`npm start\`.

export const environment = {
  production: false,
  API_URL: ${JSON.stringify(apiUrl)}
};
`;

fs.mkdirSync(path.dirname(TARGET), { recursive: true });
fs.writeFileSync(TARGET, contents);
console.log(`[set-env] wrote ${path.relative(process.cwd(), TARGET)} (API_URL=${apiUrl})`);
